### PR TITLE
Added support for grunt templates to the languages settings

### PR DESCRIPTION
**Pull request by LaurentGoderre**

### CODE REVIEW

**Comment by LaurentGoderre** [comment]
@ain @jonschlinkert what do you guys think about this?

**Comment by jonschlinkert** [comment]
sorry, didn't see this until you closed it. I think you guys are much more knowledgeable about this than me, so I defer to your wisdom

**Comment by LaurentGoderre** [comment]
I opened this not realized I had screwed up with my grunt file

**Comment by jonschlinkert** [comment]
ha, no prob. We've all done it

**Pull request closed without merging**
